version: 2.1

orbs:
  codacy: codacy/base@6.1.4
  codacy_plugins_test: codacy/plugins-test@0.15.4

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/shell:
          name: publish_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy_plugins_test/run:
          name: plugins_test
          requires:
            - publish_local
      - codacy/publish_docker:
          name: publish_dockerhub
          filters:
            branches:
              only: master
          requires:
            - publish_local
            - plugins_test
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - publish_dockerhub
